# Generated by Django 5.2.4 on 2025-12-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('IN_SERVICE', 'In Service'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
