# Generated by Django 5.2.8 on 2026-01-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
