# Generated by Django 5.2.8 on 2026-02-12 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('EN_ROUTE', 'En Route'), ('IN_SERVICE', 'In Service'), ('COMPLETE', 'Complete'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
