server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
        
        # This line fixes the Chrome CSP error
        add_header Content-Security-Policy "default-src * 'self' 'unsafe-inline' 'unsafe-eval'; protocol-data:; img-src * 'self' data: blob:; font-src * 'self' data:;";
    }
}