# Generated by Django 5.2.8 on 2025-11-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='The email for the carwash owner, will be used to create their user account upon approval.', max_length=255, null=True, unique=True),
        ),
    ]
