# Generated by Django 5.2.8 on 2025-12-27 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0002_alter_carwashprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='license_scan_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='validation_status',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='national_id',
            field=models.CharField(default='0000000000', help_text='National Identity Number', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='personnel_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers_photos/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default='09000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20),
        ),
    ]
