# Generated by Django 5.2.8 on 2026-01-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0003_remove_driver_license_scan_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carwashprofile',
            name='license_photo_url',
        ),
        migrations.AddField(
            model_name='carwashprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='carwash_licenses/'),
        ),
        migrations.AddField(
            model_name='carwashprofile',
            name='ownership_image',
            field=models.ImageField(blank=True, null=True, upload_to='carwash_ownerships/'),
        ),
    ]
