# Generated by Django 5.2.4 on 2026-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carwash', '0004_remove_carwashprofile_license_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carwashprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='carwashprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
